"""Add url_visits model

Revision ID: 8feed164d75a
Revises: 73c6060fe4a8
Create Date: 2025-07-03 14:36:33.637650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8feed164d75a"
down_revision: Union[str, Sequence[str], None] = "73c6060fe4a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["urls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_url_visits_url_id"), "url_visits", ["url_id"], unique=False
    )
    op.drop_constraint(op.f("urls_short_url_key"), "urls", type_="unique")
    op.create_index(op.f("ix_urls_short_url"), "urls", ["short_url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_short_url"), table_name="urls")
    op.create_unique_constraint(
        op.f("urls_short_url_key"),
        "urls",
        ["short_url"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_url_visits_url_id"), table_name="url_visits")
    op.drop_table("url_visits")
    # ### end Alembic commands ###
