"""Add max_ttl_minutes to user table

Revision ID: 00c4173ca2aa
Revises: 73c6060fe4a8
Create Date: 2025-07-02 11:59:42.702818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c4173ca2aa'
down_revision: Union[str, Sequence[str], None] = '73c6060fe4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_ttl_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_ttl_minutes')
    # ### end Alembic commands ###
